#!/bin/sh 
LOGFILE=/var/log/flsample/access_log
ERRLOGFILE=/var/log/flsample/error_log
RUNDIR=/home/www-bin/flsample/script

echo $RUNDIR/flsample_server.pl
/home/www-bin/flsample/script/flsample_server.pl -p 3999 >>$LOGFILE 2>>$ERRLOGFILE  
